name: 'Deploy to Vuepress'
description: 'This action will handle the building and deploying process Vuepress to GitHub Pages.'
author: 'TestTheDocs'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'orange'
