name: 'Deploy to vuepress'
description: 'This action will handle the building and deploying process of your vuepress to GitHub Pages.'
author: 'guoqiang.fu <434543162@qq.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'orange'
